### PR TITLE
Fix chinese translations, make it more localized

### PR DESCRIPTION
**Pull request by xtherk**
## What's fixed

Fix chinese translations, make it more localized

### CODE REVIEW

**Review by AdminHcat — CHANGES_REQUESTED** [review]
中文语境不应以英文句号为结尾

**Comment by xtherk** [comment]
> 中文语境不应以英文句号为结尾

确实，我只是保持跟之前一致，没有大幅度修改。

**Comment by master7720** [comment]
google translate time

**Comment by Col-E** [comment]
Thanks for the translation updates 👍

**Pull request merged**
