### PR TITLE
 Refactor auto-completion, classpath util & related code

### PR DESCRIPTION
**Pull request by andylizi**
* Rewrite some code
* Rewrite some more code related to the code mentioned above.
* Add support for arrays when completing descriptor (e.g `[Ljava/lang/String;`)
* Add unit tests for auto-completion (incomplete)
* Add [JUnit Jupiter Params](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests) component to test dependencies
* Add [Hamcrest](https://hamcrest.org/JavaHamcrest/) to test dependencies
* Partially fix auto-completion doesn't suggest any of the bootstrap classes - see #134.

### CODE REVIEW

**Comment by Col-E** [comment]
Currently this causes `mvn test` to fail:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running me.coley.recaf.AssemblerTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.127 s - in me.coley.recaf.AssemblerTest
[INFO] Running me.coley.recaf.AutoCompleteTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.002 s - in me.coley.recaf.AutoCompleteTest
[INFO] Running me.coley.recaf.FormatFactoryTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.242 s - in me.coley.recaf.FormatFactoryTest
[INFO] Running me.coley.recaf.GraphTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.011 s - in me.coley.recaf.GraphTest
[INFO] Running me.coley.recaf.HierarchyTest
[ERROR] Tests run: 6, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.069 s <<< FAILURE! - in me.coley.recaf.HierarchyTest
[ERROR] testHierarchyBuilder  Time elapsed: 0.014 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <8> but was: <7>
        at me.coley.recaf.HierarchyTest.testHierarchyBuilder(HierarchyTest.java:93)

[ERROR] testIsLibrary  Time elapsed: 0.006 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
        at me.coley.recaf.HierarchyTest.testIsLibrary(HierarchyTest.java:110)

[INFO] Running me.coley.recaf.InputTest
[INFO:6/16/19 12:25 PM] Rename test/Jedi -> test/GoodGuy
[INFO:6/16/19 12:25 PM] Rename test/Jedi -> test/GoodGuy
[INFO:6/16/19 12:25 PM] Rename test/Jedi -> test/GoodGuy
[INFO:6/16/19 12:25 PM] Rename test/Jedi -> test/GoodGuy
[INFO:6/16/19 12:25 PM] Rename test/Jedi -> test/GoodGuy
[INFO:6/16/19 12:25 PM] Rename test/Jedi -> test/GoodGuy
[INFO:6/16/19 12:25 PM] Rename test/Jedi -> test/GoodGuy
[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.122 s <<< FAILURE! - in me.coley.recaf.InputTest
[ERROR] testClassRename  Time elapsed: 0.035 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <9> but was: <8>
        at me.coley.recaf.InputTest.testClassRename(InputTest.java:94)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   HierarchyTest.testHierarchyBuilder:93 expected: <8> but was: <7>
[ERROR]   HierarchyTest.testIsLibrary:110 expected: <true> but was: <false>
[ERROR]   InputTest.testClassRename:94 expected: <9> but was: <8>
[INFO]
[ERROR] Tests run: 28, Failures: 3, Errors: 0, Skipped: 1
```

Looks like each case is because the hierarchy is missing a single element. Did the change to [class loading](https://github.com/Col-E/Recaf/pull/136/files?file-filters%5B%5D=.java#diff-fa320622e182cee3278de709d2d627ed) cause this?

**Comment by andylizi** [comment]
Okay this is weird...
recaf-test-idea
recaf-test-maven
recaf-test-maven-from-idea
Need more investigation.

---

> Did the change to [class loading](https://github.com/Col-E/Recaf/pull/136/files?file-filters%5B%5D=.java#diff-fa320622e182cee3278de709d2d627ed) cause this?

It shouldn't because `Classpath.getSystemClass(name)` is [directly implemented](136/files#diff-4341b80f9da9c7e61e342dd3cd73d2dfR71) as `Class.forName(className, false, Classpath.scl)`, so it should just be a shortcut...
This is super weird.

**Comment by andylizi** [comment]
Done.

Note to myself: Never close a classloader without knowing EXACTLY what I'm doing...

**Comment by Col-E** [comment]
🤣 Classloading sure is a mystical beast.

**Pull request merged**
