### PR TITLE
Add scripts and resources to install recaf as GNU/Linux app

### PR DESCRIPTION
**Pull request by Tigermouthbear**
## What's new
This PR adds the necessary scripts to install Recaf as a GUI and CLI application on GNU/Linux systems. I also wrote an AUR package for Recaf, but am waiting on this PR to be accepted to release it.

### CODE REVIEW

**Comment by JohnShiozo** [comment]
based

**Comment by Col-E** [comment]
I'm no linux user so I don't have any opinions on the subject. Just wondering what the setup is that requires this to be in the main repo. I was under the assumption the AUR-side of things could include these items:

For example:

* https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=recaf

**Comment by Tigermouthbear** [comment]
I didn't realize there was already an AUR package. This PR is still valid for installing on non pacman based systems or installing beta and older releases. It would also be nice to not have the desktop and start files not hard coded in the AUR package.

**Comment by Tigermouthbear** [comment]
closed bc windows users

**Pull request closed without merging**
