### PR TITLE
Add ability to set Look & Feel via environment variable.

### PR DESCRIPTION
**Pull request by michaelsavich**
Hi, I saw your project and thought it looked interesting. I noticed you hardcoded the Look & Feel, so I added the ability to set the it using the environment variable COL_RECAF_LAF. Note that as far as I know this only seems to work when the app is launched from the command line.

### CODE REVIEW

**Comment by Col-E** [comment]
Thanks! How would this look when invoked from command line?

**Comment by michaelsavich** [comment]
Here's an image of how it looks with the macOS "Aqua" look and feel: https://imgur.com/a/u4fRG

Also, setLookAndFeel is a method I added to Recaf.java. If you pass null to setLookAndFeel, it uses the default. I chose that approach to minimize the number of if-else branches.

**Comment by Col-E** [comment]
Thanks for the contribution!

**Comment by Col-E** [comment]
Expanded upon the idea in https://github.com/Col-E/Recaf/commit/98b6baebbd078ebdb723993f0ccae408f8b26650, which moves LAF application to the options menu. The themes are populated from UiManager's installed theme list. You can even swap LAF's at runtime too! 

For example I started with Nimbus and swapped to windows *(Both with different windows themes applied)*

javaw_2017-10-16_04-10-17
javaw_2017-10-16_04-13-05
javaw_2017-10-16_04-11-53

**Pull request merged**
