### PR TITLE
Add tab press for indent code in SyntaxArea

### PR DESCRIPTION
**Pull request by Amejonah1200**
## What's new
recaf

https://github.com/Col-E/recaf-3x-issues/issues/102
It's this feature, but it adds only a `\t` before each line.

### CODE REVIEW

**Comment by Amejonah1200** [comment]
@Col-E any other needs to fulfill?

**Comment by Col-E** [comment]
Not as far as I can tell, ready to merge if you're done 👍

**Comment by Amejonah1200** [comment]
@Col-E added some comments, it can be merged now

**Comment by Amejonah1200** [comment]
Hmmm, what about spaces tho? Should I just add the possibility to press space for having spaces?

**Pull request merged**
