### PR TITLE
Add new zh-cn translations and optimize old translations

### PR DESCRIPTION
**Pull request by HyrKG**
## What's new
Chinese translation can be displayed normally in most places now, and used more understandable expressions.

### CODE REVIEW

**Comment by xxDark** [comment]
Hello, thanks for the contribution
Master branch is currently in limbo state and not actively maintained, if you want to improve CN translations, it would be awesome if you do that on `dev3` branch.

**Comment by HyrKG** [comment]
I'll pull it again on dev3 branch later

**Comment by HyrKG** [comment]
I accidentally closed it XD

**Comment by JohnShiozo** [comment]
Lol

**Pull request closed without merging**
