### PR TITLE
fix: remove outdated JavaParser code

### PR DESCRIPTION
**Pull request by xxDark**
## What's fixed

This issue was fixed in 3.15.17

### CODE REVIEW

**Comment by Col-E** [comment]
It's been a long time since I made that class because of whatever the problem was, but I recall it was due to something in RichTextFX, not JavaParser. I have no clue what the issue was, what triggered it, and if it's actually been fixed.

**Comment by Col-E** [comment]
Commenting to ping regarding prior commit. 
I don't see anything in their change-logs regarding the problem.

**Comment by xxDark** [comment]
> 
> 
> Commenting to ping regarding prior commit.
> I don't see anything in their change-logs regarding the problem.

https://github.com/javaparser/javaparser/issues/2437

**Comment by Col-E** [comment]
Hmmm... If thats what propagated up and caused the UI to spaz out that's pretty interesting. I'll see if I can reproduce the old behavior and swap out with these changes. Will merge after a short bit of testing.

**Pull request merged**
